/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 11:36:31 GMT 2026
 */

package org.joda.time.format;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.Months;
import org.joda.time.MutablePeriod;
import org.joda.time.PeriodType;
import org.joda.time.ReadablePeriod;
import org.joda.time.Weeks;
import org.joda.time.chrono.CopticChronology;
import org.joda.time.format.PeriodFormat;
import org.joda.time.format.PeriodFormatter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PeriodFormat_ESTest extends PeriodFormat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PeriodFormatter periodFormatter0 = PeriodFormat.wordBased();
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      StringBuffer stringBuffer0 = new StringBuffer();
      Months months0 = Months.months(0);
      Locale locale0 = Locale.CHINESE;
      periodFormat_DynamicWordBased0.printTo(stringBuffer0, (ReadablePeriod) months0, locale0);
      assertEquals(3, stringBuffer0.length());
      assertEquals("0\u4E2A\u6708", stringBuffer0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PeriodFormatter periodFormatter0 = PeriodFormat.getDefault();
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      Weeks weeks0 = Weeks.THREE;
      Locale locale0 = Locale.PRC;
      StringWriter stringWriter0 = new StringWriter();
      periodFormat_DynamicWordBased0.printTo((Writer) stringWriter0, (ReadablePeriod) weeks0, locale0);
      assertEquals("3\u5468", stringWriter0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Locale locale0 = Locale.CANADA;
      PeriodFormatter periodFormatter0 = PeriodFormat.wordBased(locale0);
      assertTrue(periodFormatter0.isPrinter());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        PeriodFormat.wordBased((Locale) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Locale locale0 = Locale.SIMPLIFIED_CHINESE;
      CopticChronology copticChronology0 = CopticChronology.getInstance();
      MutablePeriod mutablePeriod0 = new MutablePeriod((-540L), (-540L), copticChronology0);
      PeriodFormatter periodFormatter0 = PeriodFormat.getDefault();
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      int int0 = periodFormat_DynamicWordBased0.parseInto(mutablePeriod0, "5_%0&?5 V1ZG8F@", 1, locale0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CopticChronology copticChronology0 = CopticChronology.getInstance();
      MutablePeriod mutablePeriod0 = new MutablePeriod((-540L), (-540L), copticChronology0);
      PeriodFormatter periodFormatter0 = PeriodFormat.getDefault();
      StringWriter stringWriter0 = new StringWriter(1);
      periodFormatter0.printTo((Writer) stringWriter0, (ReadablePeriod) mutablePeriod0);
      assertTrue(periodFormatter0.isParser());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Locale locale0 = Locale.SIMPLIFIED_CHINESE;
      CopticChronology copticChronology0 = CopticChronology.getInstance();
      MutablePeriod mutablePeriod0 = new MutablePeriod((-540L), (-540L), copticChronology0);
      PeriodFormatter periodFormatter0 = PeriodFormat.getDefault();
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      int int0 = periodFormat_DynamicWordBased0.calculatePrintedLength(mutablePeriod0, locale0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Locale locale0 = Locale.ENGLISH;
      PeriodFormatter periodFormatter0 = PeriodFormat.wordBased(locale0);
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      int int0 = periodFormat_DynamicWordBased0.countFieldsToPrint((ReadablePeriod) null, (-292275054), (Locale) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PeriodFormatter periodFormatter0 = PeriodFormat.wordBased();
      PeriodFormat.DynamicWordBased periodFormat_DynamicWordBased0 = new PeriodFormat.DynamicWordBased(periodFormatter0);
      PeriodType periodType0 = PeriodType.yearMonthDayTime();
      MutablePeriod mutablePeriod0 = new MutablePeriod((-1573L), periodType0);
      int int0 = periodFormat_DynamicWordBased0.parseInto(mutablePeriod0, "", 529, (Locale) null);
      assertEquals(529, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      PeriodFormat periodFormat0 = new PeriodFormat();
  }
}
