/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 12:20:06 GMT 2026
 */

package tools.jackson.core.io.schubfach;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tools.jackson.core.io.schubfach.MathUtils;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MathUtils_ESTest extends MathUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      long long0 = MathUtils.pow10(0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = MathUtils.flog2pow10(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = MathUtils.flog2pow10(703);
      assertEquals(2335, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = MathUtils.flog10threeQuartersPow2(1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = MathUtils.flog10threeQuartersPow2(3973);
      assertEquals(1195, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = MathUtils.flog10pow2(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = MathUtils.flog10pow2(3533);
      assertEquals(1063, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.g1(3291);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7230
         //
         verifyException("tools.jackson.core.io.schubfach.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.g0((-2110));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -3571
         //
         verifyException("tools.jackson.core.io.schubfach.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = MathUtils.flog10pow2((-267));
      assertEquals((-81), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.pow10((-885));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -885
         //
         verifyException("tools.jackson.core.io.schubfach.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = MathUtils.flog10threeQuartersPow2((-885));
      assertEquals((-267), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      long long0 = MathUtils.g0((-267));
      assertEquals(3991647091870204227L, long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = MathUtils.flog2pow10((-81));
      assertEquals((-270), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      long long0 = MathUtils.g1((-267));
      assertEquals(8938889586303418605L, long0);
  }
}
