/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 11:53:15 GMT 2026
 */

package tools.jackson.core.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataOutputStream;
import java.io.OutputStream;
import java.io.StringWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;
import tools.jackson.core.ErrorReportConfiguration;
import tools.jackson.core.JsonEncoding;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.JsonToken;
import tools.jackson.core.ObjectWriteContext;
import tools.jackson.core.PrettyPrinter;
import tools.jackson.core.StreamReadConstraints;
import tools.jackson.core.StreamWriteConstraints;
import tools.jackson.core.filter.FilteringGeneratorDelegate;
import tools.jackson.core.filter.TokenFilter;
import tools.jackson.core.filter.TokenFilterContext;
import tools.jackson.core.io.ContentReference;
import tools.jackson.core.io.IOContext;
import tools.jackson.core.io.SerializedString;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.core.json.UTF8JsonGenerator;
import tools.jackson.core.json.WriterBasedJsonGenerator;
import tools.jackson.core.util.BufferRecycler;
import tools.jackson.core.util.ByteArrayBuilder;
import tools.jackson.core.util.DefaultPrettyPrinter;
import tools.jackson.core.util.JsonGeneratorDelegate;
import tools.jackson.core.util.JsonpCharacterEscapes;
import tools.jackson.core.util.MinimalPrettyPrinter;
import tools.jackson.core.util.Named;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenFilterContext_ESTest extends TokenFilterContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      tokenFilterContext0.reset(5, tokenFilter0, tokenFilter_Inclusion0, false);
      tokenFilterContext0.toString();
      assertEquals("?", tokenFilterContext0.typeDesc());
      assertFalse(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildObjectContext(tokenFilter0, object0, false);
      assertEquals("Object", tokenFilterContext2.typeDesc());
      assertEquals(2, tokenFilterContext2.getNestingDepth());
      assertFalse(tokenFilterContext2.isStartHandled());
      
      TokenFilterContext tokenFilterContext3 = tokenFilterContext1.findChildOf(tokenFilterContext1);
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertNull(tokenFilterContext3);
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(0, tokenFilterContext1.getEntryCount());
      assertTrue(tokenFilterContext1.inArray());
      assertTrue(tokenFilterContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.reset(545, tokenFilter0, "l2<I~GT,8agh", false);
      assertFalse(tokenFilterContext0.isStartHandled());
      
      JsonToken jsonToken0 = tokenFilterContext0.nextTokenToRead();
      assertEquals(JsonToken.START_ARRAY, jsonToken0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildArrayContext(tokenFilter0, tokenFilterContext0, false);
      tokenFilterContext2.skipParentChecks();
      assertTrue(tokenFilterContext2.inArray());
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertEquals(2, tokenFilterContext2.getNestingDepth());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals("root", tokenFilterContext0.typeDesc());
      assertEquals(0, tokenFilterContext2.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      Object object0 = new Object();
      tokenFilterContext0.reset(123, tokenFilter0, object0, false);
      // Undeclared exception!
      try { 
        tokenFilterContext1.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      tokenFilterContext0.reset(5, tokenFilter0, tokenFilter_Inclusion0, false);
      assertFalse(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0.writePath(filteringGeneratorDelegate0);
      assertEquals(0, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilter tokenFilter1 = new TokenFilter();
      tokenFilterContext0.checkValue(tokenFilter1);
      assertEquals(1, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      TokenFilter tokenFilter1 = new TokenFilter();
      tokenFilterContext1.checkValue(tokenFilter1);
      assertEquals(1, tokenFilterContext1.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.checkValue(tokenFilter0);
      tokenFilterContext0.checkValue(tokenFilter0);
      assertEquals(1, tokenFilterContext0.getCurrentIndex());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, false);
      TokenFilter tokenFilter1 = new TokenFilter();
      tokenFilterContext1.checkValue(tokenFilter1);
      assertTrue(tokenFilterContext0.inRoot());
      assertEquals("Object", tokenFilterContext1.typeDesc());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext1._child = tokenFilterContext0;
      assertTrue(tokenFilterContext0.inRoot());
      
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildObjectContext(tokenFilter0, "/", true);
      assertEquals(0, tokenFilterContext2.getEntryCount());
      assertTrue(tokenFilterContext2.inObject());
      assertTrue(tokenFilterContext2.isStartHandled());
      assertTrue(tokenFilterContext1.isStartHandled());
      assertSame(tokenFilterContext2, tokenFilterContext0);
      assertEquals(0, tokenFilterContext1.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilter tokenFilter1 = TokenFilter.INCLUDE_ALL;
      tokenFilterContext0._child = tokenFilterContext0;
      tokenFilterContext0.createChildObjectContext(tokenFilter1, (Object) null, false);
      assertFalse(tokenFilterContext0.isStartHandled());
      assertTrue(tokenFilterContext0.inObject());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, tokenFilter0, true);
      assertTrue(tokenFilterContext1.isStartHandled());
      assertTrue(tokenFilterContext1.inObject());
      
      TokenFilterContext tokenFilterContext2 = tokenFilterContext0.createChildArrayContext(tokenFilter0, "Internal error on SymbolTable.rehash(): had %d entries; now have %d", true);
      assertEquals(1, tokenFilterContext2.getNestingDepth());
      assertEquals("Array", tokenFilterContext2.typeDesc());
      assertTrue(tokenFilterContext2.isStartHandled());
      assertFalse(tokenFilterContext0.hasCurrentIndex());
      assertSame(tokenFilterContext2, tokenFilterContext1);
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.skipParentChecks();
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, true);
      assertTrue(tokenFilterContext1.isStartHandled());
      
      TokenFilterContext tokenFilterContext2 = tokenFilterContext0.createChildArrayContext(tokenFilter0, (Object) null, false);
      assertEquals(1, tokenFilterContext2.getNestingDepth());
      assertFalse(tokenFilterContext2.isStartHandled());
      assertFalse(tokenFilterContext2.hasCurrentIndex());
      assertSame(tokenFilterContext2, tokenFilterContext1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.skipParentChecks();
      tokenFilterContext0.setPropertyName("[{)YU)U/W0 ");
      assertTrue(tokenFilterContext0.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      assertTrue(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0.reset(0, tokenFilter0, filteringGeneratorDelegate0, false);
      assertFalse(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      assertEquals("root", tokenFilterContext0.typeDesc());
      
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.reset(1, tokenFilter0, tokenFilter0, false);
      assertFalse(tokenFilterContext1.inRoot());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      Named named0 = Named.fromString("tools.jacBson.core.filter.TogenFilterCoItext");
      TokenFilterContext tokenFilterContext1 = new TokenFilterContext(125, tokenFilterContext0, tokenFilter0, named0, false);
      tokenFilterContext1.reset(2, tokenFilter0, tokenFilter0, false);
      assertFalse(tokenFilterContext0.inObject());
      assertEquals("Object", tokenFilterContext1.typeDesc());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      assertTrue(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0._startHandled = false;
      tokenFilterContext0.isStartHandled();
      assertFalse(tokenFilterContext0.inObject());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, true);
      tokenFilterContext0.checkValue(tokenFilter0);
      tokenFilterContext1.getParent();
      assertEquals(1, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.ONLY_INCLUDE_ALL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      tokenFilterContext0.skipParentChecks();
      tokenFilterContext0.getFilter();
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, tokenFilter0, false);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.findChildOf(tokenFilterContext0);
      assertNotNull(tokenFilterContext2);
      assertFalse(tokenFilterContext2.isStartHandled());
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals("root", tokenFilterContext0.typeDesc());
      assertEquals(0, tokenFilterContext2.getEntryCount());
      assertEquals("Object", tokenFilterContext2.typeDesc());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, true);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.findChildOf(tokenFilterContext0);
      assertEquals(0, tokenFilterContext2.getEntryCount());
      assertEquals("root", tokenFilterContext0.typeDesc());
      assertEquals(1, tokenFilterContext2.getNestingDepth());
      assertNotNull(tokenFilterContext2);
      assertTrue(tokenFilterContext2.isStartHandled());
      assertTrue(tokenFilterContext2.inArray());
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.checkValue(tokenFilter0);
      tokenFilterContext0.findChildOf((TokenFilterContext) null);
      assertEquals(1, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext0 = new TokenFilterContext(3696, (TokenFilterContext) null, tokenFilter0, object0, true);
      Object object1 = tokenFilterContext0.currentValue();
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertNotNull(object1);
      assertEquals("?", tokenFilterContext0.typeDesc());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(0, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.setPropertyName("xDBKHFY");
      tokenFilterContext0.currentName();
      assertTrue(tokenFilterContext0.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext0.reset(2, tokenFilter0, tokenFilterContext1, true);
      JsonGeneratorDelegate jsonGeneratorDelegate0 = new JsonGeneratorDelegate((JsonGenerator) null);
      tokenFilterContext1.closeArray(jsonGeneratorDelegate0);
      assertTrue(tokenFilterContext0.inObject());
      assertTrue(tokenFilterContext1.inArray());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0._currentName = "kBlv&";
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      JsonGeneratorDelegate jsonGeneratorDelegate0 = new JsonGeneratorDelegate((JsonGenerator) null);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.closeArray(jsonGeneratorDelegate0);
      assertNotNull(tokenFilterContext2);
      assertTrue(tokenFilterContext2.isStartHandled());
      assertEquals("root", tokenFilterContext2.typeDesc());
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertTrue(tokenFilterContext1.inArray());
      assertEquals(0, tokenFilterContext2.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectWriteContext.Base objectWriteContext_Base0 = new ObjectWriteContext.Base();
      MockFile mockFile0 = new MockFile(".9i=`8Xx\tIp:", "zFu7(3&u1V3_oQ");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator((ObjectWriteContext) objectWriteContext_Base0, (OutputStream) mockPrintStream0);
      try { 
        tokenFilterContext0.closeObject(jsonGenerator0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Current context not Object but root
         //  at [No location information]
         //
         verifyException("tools.jackson.core.JsonGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      ObjectWriteContext.Base objectWriteContext_Base0 = new ObjectWriteContext.Base();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.rawReference((Object) tokenFilterContext0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_BE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, false, jsonEncoding0);
      StringWriter stringWriter0 = new StringWriter();
      SerializedString serializedString0 = PrettyPrinter.DEFAULT_ROOT_VALUE_SEPARATOR;
      MinimalPrettyPrinter minimalPrettyPrinter0 = new MinimalPrettyPrinter();
      JsonpCharacterEscapes jsonpCharacterEscapes0 = new JsonpCharacterEscapes();
      WriterBasedJsonGenerator writerBasedJsonGenerator0 = new WriterBasedJsonGenerator(objectWriteContext_Base0, iOContext0, 4950, (-1), stringWriter0, serializedString0, minimalPrettyPrinter0, jsonpCharacterEscapes0, 34, '`');
      try { 
        tokenFilterContext0.closeArray(writerBasedJsonGenerator0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Current context not Array but root
         //  at [No location information]
         //
         verifyException("tools.jackson.core.JsonGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ContentReference contentReference0 = ContentReference.rawReference(false, (Object) "");
      TokenFilterContext tokenFilterContext0 = new TokenFilterContext(406, (TokenFilterContext) null, (TokenFilter) null, contentReference0, true);
      // Undeclared exception!
      try { 
        tokenFilterContext0.checkValue((TokenFilter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      // Undeclared exception!
      try { 
        tokenFilterContext0.appendDesc((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      boolean boolean0 = tokenFilterContext0.hasCurrentName();
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertTrue(tokenFilterContext0.inRoot());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ObjectWriteContext.Base objectWriteContext_Base0 = new ObjectWriteContext.Base();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.construct(false, (Object) null, 500, 2, errorReportConfiguration0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, false, jsonEncoding0);
      ByteArrayBuilder byteArrayBuilder0 = new ByteArrayBuilder(293);
      DataOutputStream dataOutputStream0 = new DataOutputStream(byteArrayBuilder0);
      SerializedString serializedString0 = PrettyPrinter.DEFAULT_ROOT_VALUE_SEPARATOR;
      JsonpCharacterEscapes jsonpCharacterEscapes0 = JsonpCharacterEscapes.instance();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext_Base0, iOContext0, 500, 50000, dataOutputStream0, serializedString0, jsonpCharacterEscapes0, defaultPrettyPrinter0, 1, '\"');
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate(uTF8JsonGenerator0, (TokenFilter) null, tokenFilter_Inclusion0, false);
      filteringGeneratorDelegate0.writeObjectPropertyStart("qsHUt");
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.getParent();
      assertTrue(tokenFilterContext1.hasCurrentName());
      assertEquals("Object", tokenFilterContext0.typeDesc());
      assertEquals(1, tokenFilterContext0.getNestingDepth());
      assertEquals("root", tokenFilterContext1.typeDesc());
      assertEquals(0, tokenFilterContext1.getEntryCount());
      assertFalse(tokenFilterContext0.isStartHandled());
      assertTrue(tokenFilterContext1.isStartHandled());
      assertNotNull(tokenFilterContext1);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.getParent();
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0._child = tokenFilterContext0;
      tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, true);
      tokenFilterContext0.setPropertyName(">q");
      StringBuilder stringBuilder0 = new StringBuilder("~1");
      tokenFilterContext0.appendDesc(stringBuilder0);
      assertTrue(tokenFilterContext0.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, false);
      StringBuilder stringBuilder0 = new StringBuilder("~1");
      tokenFilterContext1.appendDesc(stringBuilder0);
      assertEquals("~1/{?}", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      StringBuilder stringBuilder0 = new StringBuilder("~1");
      tokenFilterContext1.appendDesc(stringBuilder0);
      assertEquals("~1/[0]", stringBuilder0.toString());
      assertEquals("Array", tokenFilterContext1.typeDesc());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext1 = new TokenFilterContext(1494, tokenFilterContext0, tokenFilter0, object0, false);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.findChildOf((TokenFilterContext) null);
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertTrue(tokenFilterContext2.inRoot());
      assertEquals(0, tokenFilterContext2.getEntryCount());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertNotNull(tokenFilterContext2);
      assertEquals("?", tokenFilterContext1.typeDesc());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0._child = tokenFilterContext0;
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, true);
      tokenFilterContext0.setPropertyName(">q");
      JsonToken jsonToken0 = tokenFilterContext1.nextTokenToRead();
      assertTrue(tokenFilterContext0.hasCurrentName());
      assertEquals(JsonToken.PROPERTY_NAME, jsonToken0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.setPropertyName(">q");
      tokenFilterContext0.nextTokenToRead();
      assertTrue(tokenFilterContext0.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, false);
      assertFalse(tokenFilterContext1.isStartHandled());
      
      tokenFilterContext1.nextTokenToRead();
      assertTrue(tokenFilterContext1.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext1.nextTokenToRead();
      assertTrue(tokenFilterContext1.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      assertTrue(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0.nextTokenToRead();
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext1.setPropertyName("");
      tokenFilterContext1.closeObject((JsonGenerator) null);
      assertTrue(tokenFilterContext1.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      assertTrue(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0._startHandled = false;
      tokenFilterContext0.skipParentChecks();
      tokenFilterContext0.closeObject((JsonGenerator) null);
      assertEquals(0, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      // Undeclared exception!
      try { 
        tokenFilterContext0.closeObject((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      assertFalse(tokenFilterContext1.isStartHandled());
      assertNotNull(tokenFilterContext1);
      
      JsonGeneratorDelegate jsonGeneratorDelegate0 = new JsonGeneratorDelegate((JsonGenerator) null);
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.closeArray(jsonGeneratorDelegate0);
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertFalse(tokenFilterContext2.inArray());
      assertTrue(tokenFilterContext1.inArray());
      assertEquals(0, tokenFilterContext2.getEntryCount());
      assertNotNull(tokenFilterContext2);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      JsonGeneratorDelegate jsonGeneratorDelegate0 = new JsonGeneratorDelegate((JsonGenerator) null);
      // Undeclared exception!
      try { 
        tokenFilterContext0.closeArray(jsonGeneratorDelegate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.JsonGeneratorDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext0._startHandled = false;
      // Undeclared exception!
      try { 
        tokenFilterContext1.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, false);
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildObjectContext(tokenFilter0, object0, false);
      // Undeclared exception!
      try { 
        tokenFilterContext2.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      tokenFilterContext0.setPropertyName("~0");
      // Undeclared exception!
      try { 
        tokenFilterContext1.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, false);
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildObjectContext(tokenFilter0, object0, false);
      // Undeclared exception!
      try { 
        tokenFilterContext2.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilter tokenFilter1 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter1, (Object) null, false);
      Object object0 = new Object();
      TokenFilterContext tokenFilterContext2 = tokenFilterContext1.createChildObjectContext(tokenFilter0, object0, false);
      // Undeclared exception!
      try { 
        tokenFilterContext2.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter0, (Object) null, false);
      tokenFilterContext0.skipParentChecks();
      // Undeclared exception!
      try { 
        tokenFilterContext1.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      tokenFilterContext0.setPropertyName("tools.jackson.core.filter.TokenFilterContext");
      // Undeclared exception!
      try { 
        tokenFilterContext0.writePath((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilter tokenFilter1 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext1 = tokenFilterContext0.createChildObjectContext(tokenFilter1, (Object) null, true);
      assertNotNull(tokenFilterContext1);
      
      tokenFilterContext1.writePath((JsonGenerator) null);
      assertEquals(1, tokenFilterContext1.getNestingDepth());
      assertTrue(tokenFilterContext1.isStartHandled());
      assertTrue(tokenFilterContext1.inObject());
      assertEquals(0, tokenFilterContext1.getEntryCount());
      assertEquals("root", tokenFilterContext0.typeDesc());
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      assertTrue(tokenFilterContext0.isStartHandled());
      
      tokenFilterContext0.writePath((JsonGenerator) null);
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertEquals("root", tokenFilterContext0.typeDesc());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.skipParentChecks();
      tokenFilterContext0.writePath((JsonGenerator) null);
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertTrue(tokenFilterContext0.inRoot());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.setPropertyName("Unexpected low surrogate in property name (%04X) without preceding high surrogate");
      // Undeclared exception!
      try { 
        tokenFilterContext0.ensurePropertyNameWritten((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.TokenFilterContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.ensurePropertyNameWritten((JsonGenerator) null);
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.inRoot());
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0._child = tokenFilterContext0;
      assertTrue(tokenFilterContext0._child.inRoot());
      
      tokenFilterContext0.createChildArrayContext(tokenFilter0, tokenFilter0, true);
      assertTrue(tokenFilterContext0.inArray());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.assignCurrentValue(tokenFilter0);
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertTrue(tokenFilterContext0.inRoot());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      TokenFilter tokenFilter1 = tokenFilterContext0.getFilter();
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertNotNull(tokenFilter1);
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      TokenFilter tokenFilter0 = new TokenFilter();
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.ONLY_INCLUDE_ALL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      TokenFilterContext tokenFilterContext0 = filteringGeneratorDelegate0._filterContext;
      tokenFilterContext0.currentValue();
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(tokenFilterContext0.isStartHandled());
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals("root", tokenFilterContext0.typeDesc());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      boolean boolean0 = tokenFilterContext0.isStartHandled();
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertTrue(boolean0);
      assertTrue(tokenFilterContext0.inRoot());
      assertEquals(0, tokenFilterContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.currentName();
      assertEquals(0, tokenFilterContext0.getEntryCount());
      assertEquals(0, tokenFilterContext0.getNestingDepth());
      assertEquals("root", tokenFilterContext0.typeDesc());
      assertTrue(tokenFilterContext0.isStartHandled());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilterContext tokenFilterContext0 = TokenFilterContext.createRootContext(tokenFilter0);
      tokenFilterContext0.setPropertyName("s#.IwV7)ytW");
      boolean boolean0 = tokenFilterContext0.hasCurrentName();
      assertTrue(boolean0);
  }
}
