/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 11:59:13 GMT 2026
 */

package tools.jackson.core.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayOutputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.PipedOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;
import tools.jackson.core.io.DataOutputAsStream;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataOutputAsStream_ESTest extends DataOutputAsStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("tools.jackson.core.io.DataOutputAsStream");
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockPrintStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      byte[] byteArray0 = new byte[3];
      dataOutputAsStream0.write(byteArray0, 1, 0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream((DataOutput) null);
      byte[] byteArray0 = new byte[6];
      // Undeclared exception!
      try { 
        dataOutputAsStream0.write(byteArray0, (int) (byte)0, (int) (byte)108);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.io.DataOutputAsStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("g/J)0;2GR\"}", true);
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockFileOutputStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        dataOutputAsStream0.write(byteArray0, (int) (byte) (-50), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -50
         //
         verifyException("org.evosuite.runtime.vfs.VFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      DataOutputStream dataOutputStream0 = new DataOutputStream(pipedOutputStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      byte[] byteArray0 = new byte[9];
      try { 
        dataOutputAsStream0.write(byteArray0, (int) (byte) (-1), (int) (byte) (-1));
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream((DataOutput) null);
      byte[] byteArray0 = new byte[6];
      // Undeclared exception!
      try { 
        dataOutputAsStream0.write(byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.io.DataOutputAsStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream((DataOutput) null);
      // Undeclared exception!
      try { 
        dataOutputAsStream0.write(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.io.DataOutputAsStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      DataOutputStream dataOutputStream0 = new DataOutputStream(byteArrayOutputStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      dataOutputAsStream0.write(1781);
      assertEquals("\u00F5", byteArrayOutputStream0.toString());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      DataOutputStream dataOutputStream0 = new DataOutputStream(byteArrayOutputStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      byte[] byteArray0 = new byte[5];
      dataOutputAsStream0.write(byteArray0);
      assertEquals(5, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      DataOutputStream dataOutputStream0 = new DataOutputStream(byteArrayOutputStream0);
      DataOutputAsStream dataOutputAsStream0 = new DataOutputAsStream(dataOutputStream0);
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        dataOutputAsStream0.write(byteArray0, (-101), 402);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayOutputStream", e);
      }
  }
}
