/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 14:45:44 GMT 2026
 */

package tools.jackson.core.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataOutputStream;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import java.io.StringWriter;
import java.io.Writer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;
import tools.jackson.core.ErrorReportConfiguration;
import tools.jackson.core.JsonEncoding;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.ObjectWriteContext;
import tools.jackson.core.PrettyPrinter;
import tools.jackson.core.SerializableString;
import tools.jackson.core.StreamReadConstraints;
import tools.jackson.core.StreamWriteConstraints;
import tools.jackson.core.TokenStreamFactory;
import tools.jackson.core.base.GeneratorBase;
import tools.jackson.core.filter.FilteringGeneratorDelegate;
import tools.jackson.core.filter.TokenFilter;
import tools.jackson.core.io.CharacterEscapes;
import tools.jackson.core.io.ContentReference;
import tools.jackson.core.io.IOContext;
import tools.jackson.core.io.SerializedString;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.core.json.UTF8JsonGenerator;
import tools.jackson.core.json.WriterBasedJsonGenerator;
import tools.jackson.core.util.BufferRecycler;
import tools.jackson.core.util.DefaultIndenter;
import tools.jackson.core.util.DefaultPrettyPrinter;
import tools.jackson.core.util.JsonpCharacterEscapes;
import tools.jackson.core.util.MinimalPrettyPrinter;
import tools.jackson.core.util.Separators;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultPrettyPrinter_ESTest extends DefaultPrettyPrinter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      Separators.Spacing separators_Spacing0 = Separators.Spacing.BOTH;
      Separators separators0 = new Separators("\r\n", '8', separators_Spacing0, '\"', separators_Spacing0, "rp]-h)E<ilEuePRX%h", '~', separators_Spacing0, "\r\n");
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withSeparators(separators0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter1.writeEndArray((JsonGenerator) null, (-1406));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeEndObject((JsonGenerator) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      ObjectWriteContext objectWriteContext0 = ObjectWriteContext.empty();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.redacted();
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_LE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      MockFile mockFile0 = new MockFile("*?(k7/_+yU]`l.3j(");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, true);
      SerializedString serializedString0 = new SerializedString("*?(k7/_+yU]`l.3j(");
      JsonpCharacterEscapes jsonpCharacterEscapes0 = JsonpCharacterEscapes.instance();
      byte[] byteArray0 = new byte[5];
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext0, iOContext0, 1000, (-2681), mockFileOutputStream0, serializedString0, jsonpCharacterEscapes0, defaultPrettyPrinter0, 3, 'a', byteArray0, 1093, true);
      defaultPrettyPrinter0.writeEndArray(uTF8JsonGenerator0, 0);
      assertEquals(2, uTF8JsonGenerator0.streamWriteOutputBuffered());
      assertArrayEquals(new byte[] {(byte)32, (byte)93, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = DefaultPrettyPrinter.NopIndenter.instance();
      defaultPrettyPrinter_NopIndenter0.writeIndentation((JsonGenerator) null, (-321));
      assertTrue(defaultPrettyPrinter_NopIndenter0.isInline());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = DefaultPrettyPrinter.NopIndenter.instance();
      boolean boolean0 = defaultPrettyPrinter_NopIndenter0.isInline();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = new DefaultPrettyPrinter.NopIndenter();
      assertTrue(defaultPrettyPrinter_NopIndenter0.isInline());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = DefaultPrettyPrinter.NopIndenter.instance();
      defaultPrettyPrinter_NopIndenter0.writeIndentation((JsonGenerator) null, 93);
      assertTrue(defaultPrettyPrinter_NopIndenter0.isInline());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DefaultPrettyPrinter.FixedSpaceIndenter defaultPrettyPrinter_FixedSpaceIndenter0 = DefaultPrettyPrinter.FixedSpaceIndenter.instance();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.redacted();
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF16_LE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      StringWriter stringWriter0 = new StringWriter(1323);
      SerializedString serializedString0 = PrettyPrinter.DEFAULT_ROOT_VALUE_SEPARATOR;
      MinimalPrettyPrinter minimalPrettyPrinter0 = new MinimalPrettyPrinter("tools.jackson.core.sym.PropertyNameMatcher");
      WriterBasedJsonGenerator writerBasedJsonGenerator0 = new WriterBasedJsonGenerator((ObjectWriteContext) null, iOContext0, 123, 0, stringWriter0, serializedString0, minimalPrettyPrinter0, (CharacterEscapes) null, 773, 'Y');
      defaultPrettyPrinter_FixedSpaceIndenter0.writeIndentation(writerBasedJsonGenerator0, 12000);
      assertEquals(55296, GeneratorBase.SURR1_FIRST);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DefaultPrettyPrinter.FixedSpaceIndenter defaultPrettyPrinter_FixedSpaceIndenter0 = DefaultPrettyPrinter.FixedSpaceIndenter.instance();
      boolean boolean0 = defaultPrettyPrinter_FixedSpaceIndenter0.isInline();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      defaultPrettyPrinter0.writeObjectNameValueSeparator(jsonGenerator0);
      assertEquals(3, jsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      ObjectWriteContext.Base objectWriteContext_Base0 = (ObjectWriteContext.Base)TokenStreamFactory.EMPTY_WRITE_CONTEXT;
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler(2164, 2285);
      ContentReference contentReference0 = ContentReference.rawReference(false, (Object) defaultPrettyPrinter0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_BE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      StringWriter stringWriter0 = new StringWriter(2212);
      SerializedString serializedString0 = (SerializedString)JsonFactory.DEFAULT_ROOT_VALUE_SEPARATOR;
      JsonpCharacterEscapes jsonpCharacterEscapes0 = JsonpCharacterEscapes.instance();
      WriterBasedJsonGenerator writerBasedJsonGenerator0 = new WriterBasedJsonGenerator(objectWriteContext_Base0, iOContext0, 1000, 3, stringWriter0, serializedString0, defaultPrettyPrinter0, jsonpCharacterEscapes0, 3, 's');
      defaultPrettyPrinter0.writeArrayValueSeparator(writerBasedJsonGenerator0);
      assertEquals(2, writerBasedJsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Separators separators0 = Separators.createDefaultInstance();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectWriteContext objectWriteContext0 = ObjectWriteContext.empty();
      StringWriter stringWriter0 = new StringWriter(4347);
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(objectWriteContext0, (Writer) stringWriter0);
      defaultPrettyPrinter0.beforeArrayValues(jsonGenerator0);
      assertEquals(1, jsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Separators separators0 = new Separators('%', 'N', 't');
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeStartObject((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeStartArray((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeRootValueSeparator((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Separators separators0 = new Separators();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      ObjectWriteContext objectWriteContext0 = ObjectWriteContext.empty();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.construct(false, (Object) null, errorReportConfiguration0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_BE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      byte[] byteArray0 = new byte[7];
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext0, iOContext0, 1495, 3, pipedOutputStream0, (SerializableString) null, (CharacterEscapes) null, defaultPrettyPrinter0, 91, ']', byteArray0, (-2611), false);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeRootValueSeparator(uTF8JsonGenerator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeObjectEntrySeparator((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      defaultPrettyPrinter0._nesting = 55296;
      // Undeclared exception!
      defaultPrettyPrinter0.writeEndObject(jsonGenerator0, '\"');
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.withSeparators((Separators) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.beforeArrayValues((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter$FixedSpaceIndenter", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = null;
      try {
        defaultPrettyPrinter0 = new DefaultPrettyPrinter((Separators) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      DefaultPrettyPrinter defaultPrettyPrinter1 = null;
      try {
        defaultPrettyPrinter1 = new DefaultPrettyPrinter(defaultPrettyPrinter0, (Separators) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = null;
      try {
        defaultPrettyPrinter0 = new DefaultPrettyPrinter((DefaultPrettyPrinter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      Separators separators0 = Separators.createDefaultInstance();
      DefaultPrettyPrinter defaultPrettyPrinter1 = new DefaultPrettyPrinter(defaultPrettyPrinter0, separators0);
      assertFalse(defaultPrettyPrinter1.equals((Object)defaultPrettyPrinter0));
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      DefaultPrettyPrinter defaultPrettyPrinter1 = new DefaultPrettyPrinter(defaultPrettyPrinter0);
      assertFalse(defaultPrettyPrinter1.equals((Object)defaultPrettyPrinter0));
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.ONLY_INCLUDE_ALL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, false);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeEndArray(filteringGeneratorDelegate0, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.filter.FilteringGeneratorDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      ObjectWriteContext objectWriteContext0 = ObjectWriteContext.empty();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler(500, 50000);
      ContentReference contentReference0 = ContentReference.rawReference(true, (Object) bufferRecycler0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF16_LE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(" ", true);
      SerializedString serializedString0 = (SerializedString)defaultPrettyPrinter0._rootValueSeparator;
      JsonpCharacterEscapes jsonpCharacterEscapes0 = JsonpCharacterEscapes.instance();
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext0, iOContext0, 125, 93, mockFileOutputStream0, serializedString0, jsonpCharacterEscapes0, defaultPrettyPrinter0, 1849, 'o');
      long[] longArray0 = new long[5];
      uTF8JsonGenerator0.writeArray(longArray0, 3, (-517));
      assertEquals(3, uTF8JsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      DefaultIndenter defaultIndenter0 = new DefaultIndenter("tools.jackson.core.sym.ByteQuadsCanonicalizer", " ");
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withArrayIndenter(defaultIndenter0);
      defaultPrettyPrinter1.writeStartArray(jsonGenerator0);
      assertNotSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeEndObject((JsonGenerator) null, (-812));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.ONLY_INCLUDE_ALL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate(jsonGenerator0, tokenFilter0, tokenFilter_Inclusion0, false);
      defaultPrettyPrinter0.writeEndObject(filteringGeneratorDelegate0, 56319);
      assertEquals(3, jsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = DefaultPrettyPrinter.NopIndenter.instance();
      Separators separators0 = new Separators();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withObjectIndenter(defaultPrettyPrinter_NopIndenter0);
      ObjectWriteContext.Base objectWriteContext_Base0 = (ObjectWriteContext.Base)TokenStreamFactory.EMPTY_WRITE_CONTEXT;
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler(256, 500);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, (ContentReference) null, true, jsonEncoding0);
      StringWriter stringWriter0 = new StringWriter();
      WriterBasedJsonGenerator writerBasedJsonGenerator0 = new WriterBasedJsonGenerator(objectWriteContext_Base0, iOContext0, 500, 256, stringWriter0, (SerializableString) null, defaultPrettyPrinter0, (CharacterEscapes) null, 0, ',');
      defaultPrettyPrinter1.writeEndObject(writerBasedJsonGenerator0, 91);
      assertEquals(1, writerBasedJsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      UTF8JsonGenerator uTF8JsonGenerator0 = (UTF8JsonGenerator)jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      defaultPrettyPrinter0.writeStartObject(uTF8JsonGenerator0);
      assertEquals(55296, GeneratorBase.SURR1_FIRST);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      defaultPrettyPrinter0.indentObjectsWith((DefaultPrettyPrinter.Indenter) null);
      ObjectWriteContext.Base objectWriteContext_Base0 = new ObjectWriteContext.Base();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(" ", true);
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockFileOutputStream0);
      BufferRecycler bufferRecycler0 = new BufferRecycler(50000, 100000000);
      ContentReference contentReference0 = ContentReference.construct(true, (Object) separators0, errorReportConfiguration0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_BE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, true, jsonEncoding0);
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext_Base0, iOContext0, 1000, 3651, dataOutputStream0, jsonFactory0.DEFAULT_ROOT_VALUE_SEPARATOR, (CharacterEscapes) null, defaultPrettyPrinter0, 1000, '\"');
      defaultPrettyPrinter0.writeStartObject(uTF8JsonGenerator0);
      assertFalse(uTF8JsonGenerator0.isClosed());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      defaultPrettyPrinter0.writeRootValueSeparator(jsonGenerator0);
      assertEquals(1, jsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Separators separators0 = Separators.createDefaultInstance();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.createInstance();
      assertNotSame(defaultPrettyPrinter0, defaultPrettyPrinter1);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Separators separators0 = Separators.createDefaultInstance();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0._withSpaces(true);
      assertNotSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      defaultPrettyPrinter0.indentObjectsWith((DefaultPrettyPrinter.Indenter) null);
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withObjectIndenter((DefaultPrettyPrinter.Indenter) null);
      assertSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Separators.Spacing separators_Spacing0 = Separators.Spacing.BOTH;
      Separators separators0 = new Separators((String) null, 'Y', separators_Spacing0, '-', separators_Spacing0, (String) null, '-', separators_Spacing0, (String) null);
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter.FixedSpaceIndenter defaultPrettyPrinter_FixedSpaceIndenter0 = DefaultPrettyPrinter.FixedSpaceIndenter.instance();
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withArrayIndenter(defaultPrettyPrinter_FixedSpaceIndenter0);
      assertSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0.withArrayIndenter((DefaultPrettyPrinter.Indenter) null);
      assertNotSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      DefaultIndenter defaultIndenter0 = new DefaultIndenter("tools.jackson.core.sym.ByteQuadsCanonicalizer", " ");
      defaultPrettyPrinter0.indentObjectsWith(defaultIndenter0);
      assertEquals(" ", defaultIndenter0.getEol());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      defaultPrettyPrinter0.indentArraysWith((DefaultPrettyPrinter.Indenter) null);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      DefaultIndenter defaultIndenter0 = new DefaultIndenter();
      defaultPrettyPrinter0.indentArraysWith(defaultIndenter0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeEndArray((JsonGenerator) null, (-1406));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Separators.Spacing separators_Spacing0 = Separators.Spacing.BOTH;
      Separators separators0 = new Separators((String) null, 'Y', separators_Spacing0, '-', separators_Spacing0, (String) null, '-', separators_Spacing0, (String) null);
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      DefaultPrettyPrinter defaultPrettyPrinter1 = new DefaultPrettyPrinter(defaultPrettyPrinter0, separators0);
      assertFalse(defaultPrettyPrinter1.equals((Object)defaultPrettyPrinter0));
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DefaultPrettyPrinter.NopIndenter defaultPrettyPrinter_NopIndenter0 = DefaultPrettyPrinter.NopIndenter.instance();
      boolean boolean0 = defaultPrettyPrinter_NopIndenter0.isInline();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      defaultPrettyPrinter0.indentObjectsWith((DefaultPrettyPrinter.Indenter) null);
      defaultPrettyPrinter0.beforeObjectEntries((JsonGenerator) null);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DefaultPrettyPrinter.FixedSpaceIndenter defaultPrettyPrinter_FixedSpaceIndenter0 = new DefaultPrettyPrinter.FixedSpaceIndenter();
      assertTrue(defaultPrettyPrinter_FixedSpaceIndenter0.isInline());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Separators separators0 = Separators.createDefaultInstance();
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeArrayValueSeparator((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      JsonFactory jsonFactory0 = new JsonFactory();
      MockFile mockFile0 = new MockFile("JSON", "JSON");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF8;
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator(jsonFactory0.EMPTY_WRITE_CONTEXT, (OutputStream) mockFileOutputStream0, jsonEncoding0);
      defaultPrettyPrinter0.writeObjectEntrySeparator(jsonGenerator0);
      assertEquals(3, jsonGenerator0.streamWriteOutputBuffered());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.writeObjectNameValueSeparator((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultPrettyPrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      DefaultPrettyPrinter defaultPrettyPrinter1 = defaultPrettyPrinter0._withSpaces(false);
      assertNotSame(defaultPrettyPrinter1, defaultPrettyPrinter0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Separators separators0 = PrettyPrinter.DEFAULT_SEPARATORS;
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter(separators0);
      // Undeclared exception!
      try { 
        defaultPrettyPrinter0.beforeObjectEntries((JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.DefaultIndenter", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      DefaultPrettyPrinter defaultPrettyPrinter0 = new DefaultPrettyPrinter();
      ObjectWriteContext.Base objectWriteContext_Base0 = new ObjectWriteContext.Base();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = ErrorReportConfiguration.defaults();
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF16_LE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, (ContentReference) null, false, jsonEncoding0);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      SerializedString serializedString0 = (SerializedString)defaultPrettyPrinter0._rootValueSeparator;
      byte[] byteArray0 = new byte[7];
      UTF8JsonGenerator uTF8JsonGenerator0 = new UTF8JsonGenerator(objectWriteContext_Base0, iOContext0, 93, 2365, pipedOutputStream0, serializedString0, (CharacterEscapes) null, defaultPrettyPrinter0, 0, 'f', byteArray0, 16, false);
      try { 
        defaultPrettyPrinter0.beforeArrayValues(uTF8JsonGenerator0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Pipe not connected
         //  at [No location information]
         //
         verifyException("tools.jackson.core.exc.JacksonIOException", e);
      }
  }
}
