/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 15:07:02 GMT 2026
 */

package tools.jackson.core.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonPointer;
import tools.jackson.core.ObjectReadContext;
import tools.jackson.core.filter.FilteringGeneratorDelegate;
import tools.jackson.core.filter.TokenFilter;
import tools.jackson.core.json.DupDetector;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.core.util.BufferRecycler;
import tools.jackson.core.util.JsonRecyclerPools;
import tools.jackson.core.util.SimpleStreamWriteContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleStreamWriteContext_ESTest extends SimpleStreamWriteContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(324, simpleStreamWriteContext0, 1, dupDetector0, "");
      boolean boolean0 = simpleStreamWriteContext1.writeValue();
      assertEquals(1, simpleStreamWriteContext1.getEntryCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      dupDetector0.isDup("");
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, (-1766), dupDetector0, (Object) null);
      simpleStreamWriteContext1._currentValue = (Object) "";
      try { 
        simpleStreamWriteContext1.writeName("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Duplicate Object property \"\"
         //  at [No location information]
         //
         verifyException("tools.jackson.core.util.SimpleStreamWriteContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(3568, simpleStreamWriteContext0, 0, (DupDetector) null, simpleStreamWriteContext0);
      simpleStreamWriteContext0._childToRecycle = simpleStreamWriteContext1;
      assertEquals("?", simpleStreamWriteContext0._childToRecycle.typeDesc());
      assertEquals(0, simpleStreamWriteContext0._childToRecycle.getNestingDepth());
      
      boolean boolean0 = simpleStreamWriteContext0._childToRecycle.writeName("H");
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, (TokenFilter) null, tokenFilter_Inclusion0, false);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext(filteringGeneratorDelegate0);
      assertEquals("Array", simpleStreamWriteContext1.typeDesc());
      
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext0.createChildObjectContext(dupDetector0);
      assertFalse(simpleStreamWriteContext2.inArray());
      assertSame(simpleStreamWriteContext2, simpleStreamWriteContext1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext((Object) null);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.withDupDetector((DupDetector) null);
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals("Object", simpleStreamWriteContext2.typeDesc());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
      assertEquals(1, simpleStreamWriteContext2.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.withDupDetector(dupDetector0);
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals(1, simpleStreamWriteContext2.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertTrue(simpleStreamWriteContext2.inArray());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0._gotPropertyId = true;
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.withDupDetector(dupDetector0);
      assertEquals(0, simpleStreamWriteContext1.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext1.getEntryCount());
      assertTrue(simpleStreamWriteContext1.inRoot());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      Object object0 = new Object();
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext((-1351), simpleStreamWriteContext0, (-3280), (DupDetector) null, object0);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.withDupDetector((DupDetector) null);
      assertFalse(simpleStreamWriteContext2.inRoot());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals((-3280), simpleStreamWriteContext2.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectReadContext objectReadContext0 = ObjectReadContext.empty();
      JsonParser jsonParser0 = jsonFactory0.createNonBlockingByteArrayParser(objectReadContext0);
      DupDetector dupDetector0 = DupDetector.rootDetector(jsonParser0);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0.writeValue();
      simpleStreamWriteContext0.writeValue();
      simpleStreamWriteContext0.withDupDetector(dupDetector0);
      assertEquals(1, simpleStreamWriteContext0.getCurrentIndex());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0._gotPropertyId = true;
      simpleStreamWriteContext0.hasCurrentName();
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext((Object) null);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildObjectContext(tokenFilter_Inclusion0);
      SimpleStreamWriteContext simpleStreamWriteContext3 = simpleStreamWriteContext2.getParent();
      assertNotNull(simpleStreamWriteContext3);
      assertEquals(0, simpleStreamWriteContext3.getEntryCount());
      assertFalse(simpleStreamWriteContext3.inRoot());
      assertEquals(2, simpleStreamWriteContext2.getNestingDepth());
      assertEquals("Object", simpleStreamWriteContext2.typeDesc());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
      assertEquals(1, simpleStreamWriteContext3.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, (-1766), dupDetector0, (Object) null);
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, false);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildObjectContext(filteringGeneratorDelegate0);
      simpleStreamWriteContext1.writeName("");
      simpleStreamWriteContext2.getParent();
      assertTrue(simpleStreamWriteContext1.hasCurrentName());
      assertEquals((-1765), simpleStreamWriteContext2.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext((Object) null);
      simpleStreamWriteContext0.writeValue();
      simpleStreamWriteContext1.getParent();
      assertEquals(1, simpleStreamWriteContext0.getEntryCount());
      assertTrue(simpleStreamWriteContext0.hasCurrentIndex());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      DupDetector dupDetector1 = simpleStreamWriteContext0.getDupDetector();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
      assertNotNull(dupDetector1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      Object object0 = new Object();
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(0, simpleStreamWriteContext0, 1, dupDetector0, object0);
      Object object1 = simpleStreamWriteContext1.currentValue();
      assertEquals(1, simpleStreamWriteContext1.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext1.getEntryCount());
      assertNotNull(object1);
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals("root", simpleStreamWriteContext1.typeDesc());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      Object object0 = new Object();
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(0, simpleStreamWriteContext0, 1, dupDetector0, object0);
      simpleStreamWriteContext1._currentName = "bJR;^V'']Ju[JM;IH8";
      simpleStreamWriteContext1.currentName();
      assertEquals(0, simpleStreamWriteContext1.getEntryCount());
      assertEquals(1, simpleStreamWriteContext1.getNestingDepth());
      assertTrue(simpleStreamWriteContext1.inRoot());
      assertFalse(simpleStreamWriteContext0.inArray());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, (-1766), dupDetector0, (Object) null);
      simpleStreamWriteContext1.writeName("");
      simpleStreamWriteContext1.currentName();
      assertTrue(simpleStreamWriteContext1.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.ONLY_INCLUDE_ALL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) filteringGeneratorDelegate0);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(1174, simpleStreamWriteContext0, (-1), dupDetector0, filteringGeneratorDelegate0);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildObjectContext("gW)s8!");
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals((-1), simpleStreamWriteContext1.getNestingDepth());
      assertEquals("Object", simpleStreamWriteContext2.typeDesc());
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertEquals(0, simpleStreamWriteContext2.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      Enumeration<InputStream> enumeration0 = (Enumeration<InputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      DataInputStream dataInputStream0 = new DataInputStream(sequenceInputStream0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext((-1), simpleStreamWriteContext0, (-1), dupDetector0, dataInputStream0);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildArrayContext(dupDetector0);
      assertFalse(simpleStreamWriteContext0.inArray());
      assertEquals((-1), simpleStreamWriteContext1.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext2.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals("Array", simpleStreamWriteContext2.typeDesc());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, (-1766), dupDetector0, (Object) null);
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildArrayContext(filteringGeneratorDelegate0);
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals((-1765), simpleStreamWriteContext2.getNestingDepth());
      assertTrue(simpleStreamWriteContext2.inArray());
      assertFalse(simpleStreamWriteContext0.inArray());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      JsonPointer jsonPointer0 = simpleStreamWriteContext0.pathAsPointer();
      simpleStreamWriteContext0._gotPropertyId = true;
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext(jsonPointer0);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.clearAndGetParent();
      assertEquals(0, simpleStreamWriteContext2.getEntryCount());
      assertNotNull(simpleStreamWriteContext2);
      assertTrue(simpleStreamWriteContext2.inRoot());
      assertEquals(0, simpleStreamWriteContext2.getNestingDepth());
      assertEquals(1, simpleStreamWriteContext1.getNestingDepth());
      assertTrue(simpleStreamWriteContext1.inObject());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext((Object) null);
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_NON_NULL;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildObjectContext(filteringGeneratorDelegate0);
      SimpleStreamWriteContext simpleStreamWriteContext3 = simpleStreamWriteContext2.clearAndGetParent();
      assertEquals(2, simpleStreamWriteContext2.getNestingDepth());
      assertNotNull(simpleStreamWriteContext3);
      assertEquals("Object", simpleStreamWriteContext3.typeDesc());
      assertEquals(1, simpleStreamWriteContext3.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext3.getEntryCount());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) filteringGeneratorDelegate0);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      Object object0 = new Object();
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext(object0);
      simpleStreamWriteContext0.writeValue();
      simpleStreamWriteContext0.writeValue();
      simpleStreamWriteContext1.clearAndGetParent();
      assertEquals(1, simpleStreamWriteContext0.getCurrentIndex());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, (-1766), dupDetector0, (Object) null);
      simpleStreamWriteContext1.writeName("");
      simpleStreamWriteContext1.writeValue();
      // Undeclared exception!
      try { 
        simpleStreamWriteContext1.writeName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.json.DupDetector", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0.getParent();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH;
      FilteringGeneratorDelegate filteringGeneratorDelegate0 = new FilteringGeneratorDelegate((JsonGenerator) null, tokenFilter0, tokenFilter_Inclusion0, true);
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) filteringGeneratorDelegate0);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0.hasCurrentName();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, 2, dupDetector0, (Object) null);
      boolean boolean0 = simpleStreamWriteContext1.writeValue();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertFalse(boolean0);
      assertEquals(2, simpleStreamWriteContext1.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext1.getEntryCount());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      SimpleStreamWriteContext simpleStreamWriteContext1 = new SimpleStreamWriteContext(2, simpleStreamWriteContext0, 2, dupDetector0, (Object) null);
      simpleStreamWriteContext1.writeName("");
      boolean boolean0 = simpleStreamWriteContext1.writeName("");
      assertTrue(simpleStreamWriteContext1.hasCurrentName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext((Object) null);
      boolean boolean0 = simpleStreamWriteContext1.writeName("~1");
      assertTrue(simpleStreamWriteContext1.hasCurrentName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonParser) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      boolean boolean0 = simpleStreamWriteContext0.writeName("");
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertFalse(boolean0);
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildArrayContext((Object) null);
      assertNotNull(simpleStreamWriteContext1);
      
      Object object0 = simpleStreamWriteContext0.currentValue();
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext1.createChildObjectContext(object0);
      SimpleStreamWriteContext simpleStreamWriteContext3 = simpleStreamWriteContext2.clearAndGetParent();
      assertEquals(2, simpleStreamWriteContext2.getNestingDepth());
      assertTrue(simpleStreamWriteContext2.inObject());
      assertEquals("Array", simpleStreamWriteContext1.typeDesc());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext3.getEntryCount());
      assertNotNull(simpleStreamWriteContext3);
      assertFalse(simpleStreamWriteContext0.inArray());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext((Object) null);
      assertNotNull(simpleStreamWriteContext1);
      
      Object object0 = simpleStreamWriteContext1.currentValue();
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext0.createChildObjectContext(object0);
      assertEquals(0, simpleStreamWriteContext1.getEntryCount());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(1, simpleStreamWriteContext2.getNestingDepth());
      assertSame(simpleStreamWriteContext2, simpleStreamWriteContext1);
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
      assertEquals("Object", simpleStreamWriteContext1.typeDesc());
      assertFalse(simpleStreamWriteContext2.hasCurrentName());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      simpleStreamWriteContext0.getDupDetector();
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext((DupDetector) null);
      simpleStreamWriteContext0.clearAndGetParent();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertEquals("root", simpleStreamWriteContext0.typeDesc());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      simpleStreamWriteContext0.currentName();
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
      assertTrue(simpleStreamWriteContext0.inRoot());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      JsonPointer jsonPointer0 = simpleStreamWriteContext0.pathAsPointer(false);
      SimpleStreamWriteContext simpleStreamWriteContext1 = simpleStreamWriteContext0.createChildObjectContext(jsonPointer0);
      assertNotNull(simpleStreamWriteContext1);
      assertTrue(simpleStreamWriteContext1.inObject());
      
      SimpleStreamWriteContext simpleStreamWriteContext2 = simpleStreamWriteContext0.createChildArrayContext(dupDetector0);
      assertTrue(simpleStreamWriteContext2.inArray());
      assertSame(simpleStreamWriteContext2, simpleStreamWriteContext1);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      SimpleStreamWriteContext simpleStreamWriteContext0 = SimpleStreamWriteContext.createRootContext(dupDetector0);
      JsonRecyclerPools.ConcurrentDequePool jsonRecyclerPools_ConcurrentDequePool0 = JsonRecyclerPools.ConcurrentDequePool.GLOBAL;
      BufferRecycler bufferRecycler0 = jsonRecyclerPools_ConcurrentDequePool0.createPooled();
      simpleStreamWriteContext0.assignCurrentValue(bufferRecycler0);
      assertTrue(simpleStreamWriteContext0.inRoot());
      assertEquals(0, simpleStreamWriteContext0.getNestingDepth());
      assertEquals(0, simpleStreamWriteContext0.getEntryCount());
  }
}
