/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 15:11:37 GMT 2026
 */

package tools.jackson.core.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tools.jackson.core.Version;
import tools.jackson.core.json.UTF8DataInputJsonParser;
import tools.jackson.core.util.VersionUtil;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VersionUtil_ESTest extends VersionUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = VersionUtil.parseVersionPart("9|'Rv9*0*");
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("_Ba3p\"6bl')Z_H", "_Ba3p\"6bl')Z_H", "");
      assertEquals(0, version0.getPatchLevel());
      assertEquals("", version0.getArtifactId());
      assertEquals("_Ba3p\"6bl')Z_H", version0.getGroupId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Class<UTF8DataInputJsonParser> class0 = UTF8DataInputJsonParser.class;
      Version version0 = VersionUtil.versionFor(class0);
      assertTrue(version0.isSnapshot());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("^b1=@0:8n-8<_}6w~[", "^b1=@0:8n-8<_}6w~[", "tools.jackson.core.util.VersionUtil");
      assertEquals("^b1=@0:8n-8<_}6w~[", version0.getGroupId());
      assertTrue(version0.isSnapshot());
      assertEquals(8, version0.getMinorVersion());
      assertEquals("tools.jackson.core.util.VersionUtil", version0.getArtifactId());
      assertEquals(8, version0.getPatchLevel());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.parseVersionPart((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.util.VersionUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = VersionUtil.parseVersionPart("70JtIJiYGZ");
      assertEquals(70, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = VersionUtil.parseVersionPart("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("COMBINE_UNICODE_SURROGATES_IN_UTF8", "1({*pjZD#fgp?x", "");
      assertTrue(version0.isSnapshot());
      assertEquals("1({*pjZD#fgp?x", version0.getGroupId());
      assertEquals("", version0.getArtifactId());
      assertEquals(0, version0.getMajorVersion());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("uo({fNuiMmOUFY/$MC,", "1({*pjZD#fgp?x", "");
      assertEquals(0, version0.getPatchLevel());
      assertEquals("1({*pjZD#fgp?x", version0.getGroupId());
      assertEquals("", version0.getArtifactId());
      assertEquals(0, version0.getMinorVersion());
      assertEquals(0, version0.getMajorVersion());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = VersionUtil.parseVersionPart("+11");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("", "", "aZ%8_7`87UY8");
      assertEquals("", version0.getArtifactId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion("8", "iw~XQm~%Rtv", "8");
      assertEquals("iw~XQm~%Rtv", version0.getGroupId());
      assertEquals(0, version0.getMinorVersion());
      assertEquals(0, version0.getPatchLevel());
      assertEquals("8", version0.getArtifactId());
      assertEquals(8, version0.getMajorVersion());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.parseVersion("...", "DwY", "...");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("tools.jackson.core.util.VersionUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Version version0 = VersionUtil.parseVersion((String) null, (String) null, (String) null);
      assertFalse(version0.isSnapshot());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Version version0 = VersionUtil.versionFor(class0);
      assertFalse(version0.isSnapshot());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VersionUtil versionUtil0 = new VersionUtil();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.throwInternal();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Internal error: this code path should never get executed
         //
         verifyException("tools.jackson.core.util.VersionUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.throwInternalReturnAny();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Internal error: this code path should never get executed
         //
         verifyException("tools.jackson.core.util.VersionUtil", e);
      }
  }
}
