/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 11:28:08 GMT 2026
 */

package tools.jackson.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.Closeable;
import java.io.OutputStreamWriter;
import java.io.PipedOutputStream;
import java.io.PipedReader;
import java.io.StringReader;
import java.io.StringWriter;
import java.lang.reflect.InvocationTargetException;
import java.nio.charset.Charset;
import java.nio.charset.CharsetEncoder;
import java.util.List;
import java.util.function.BiFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;
import tools.jackson.core.ErrorReportConfiguration;
import tools.jackson.core.JacksonException;
import tools.jackson.core.JsonEncoding;
import tools.jackson.core.JsonParser;
import tools.jackson.core.ObjectReadContext;
import tools.jackson.core.StreamReadConstraints;
import tools.jackson.core.StreamWriteConstraints;
import tools.jackson.core.TokenStreamFactory;
import tools.jackson.core.TokenStreamLocation;
import tools.jackson.core.filter.FilteringParserDelegate;
import tools.jackson.core.filter.TokenFilter;
import tools.jackson.core.io.ContentReference;
import tools.jackson.core.io.IOContext;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.core.json.ReaderBasedJsonParser;
import tools.jackson.core.sym.CharsToNameCanonicalizer;
import tools.jackson.core.util.BufferRecycler;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JacksonException_ESTest extends JacksonException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      InvocationTargetException invocationTargetException0 = new InvocationTargetException(mockThrowable0);
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(invocationTargetException0, (-1193));
      JacksonException.Reference jacksonException_Reference1 = (JacksonException.Reference)jacksonException_Reference0.writeReplace();
      assertEquals((-1193), jacksonException_Reference1.getIndex());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference("NlFWYJ/^U#A,");
      String string0 = jacksonException_Reference0.getDescription();
      assertEquals("java.lang.String[?]", string0);
      assertNotNull(string0);
      
      String string1 = jacksonException_Reference0.getPropertyName();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      assertNull(string1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException((Closeable) null, (String) null);
      JacksonException jacksonException1 = jacksonException0.withCause(jacksonException0);
      assertSame(jacksonException0, jacksonException1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1170);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      Object object0 = jacksonException0.processor();
      assertSame(object0, pipedReader0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(3393);
      JacksonException jacksonException0 = new JacksonException(charArrayWriter0, "N/A");
      String string0 = jacksonException0.messageSuffix();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(3393);
      JacksonException jacksonException0 = new JacksonException(charArrayWriter0, "N/A");
      jacksonException0.prependPath((Object) " 4:m", 3393);
      String string0 = jacksonException0.getPathReference();
      assertEquals("java.lang.String[3393]", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("%oqc>U@");
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference((Object) null);
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      String string0 = jacksonException0.getOriginalMessage();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      assertEquals("%oqc>U@", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("");
      String string0 = jacksonException0.getOriginalMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("");
      String string0 = jacksonException0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("tools.jackson.core.StreamReadConstraints");
      TokenStreamLocation tokenStreamLocation0 = jacksonException0.getLocation();
      assertNull(tokenStreamLocation0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ObjectReadContext.Base objectReadContext_Base0 = new ObjectReadContext.Base();
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamWriteConstraints streamWriteConstraints0 = StreamWriteConstraints.defaults();
      ErrorReportConfiguration errorReportConfiguration0 = new ErrorReportConfiguration(100000000, 500);
      BufferRecycler bufferRecycler0 = new BufferRecycler();
      ContentReference contentReference0 = ContentReference.construct(false, (Object) streamWriteConstraints0, (-2), 2, errorReportConfiguration0);
      JsonEncoding jsonEncoding0 = JsonEncoding.UTF32_LE;
      IOContext iOContext0 = new IOContext(streamReadConstraints0, streamWriteConstraints0, errorReportConfiguration0, bufferRecycler0, contentReference0, false, jsonEncoding0);
      StringReader stringReader0 = new StringReader("9JYH~`TzM9^");
      JsonFactory jsonFactory0 = new JsonFactory();
      CharsToNameCanonicalizer charsToNameCanonicalizer0 = CharsToNameCanonicalizer.createRoot((TokenStreamFactory) jsonFactory0);
      ReaderBasedJsonParser readerBasedJsonParser0 = new ReaderBasedJsonParser(objectReadContext_Base0, iOContext0, 1, 7, stringReader0, charsToNameCanonicalizer0);
      TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
      TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH;
      FilteringParserDelegate filteringParserDelegate0 = new FilteringParserDelegate(readerBasedJsonParser0, tokenFilter0, tokenFilter_Inclusion0, false, false);
      TokenStreamLocation tokenStreamLocation0 = filteringParserDelegate0.currentTokenLocation();
      JacksonException jacksonException0 = new JacksonException((Closeable) null, "9JYH~`TzM9^", tokenStreamLocation0);
      TokenStreamLocation tokenStreamLocation1 = jacksonException0.getLocation();
      assertEquals(1, tokenStreamLocation1.getLineNr());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(pipedOutputStream0, charsetEncoder0);
      ContentReference contentReference0 = ContentReference.unknown();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 24, 41, 24);
      JacksonException jacksonException0 = new JacksonException(outputStreamWriter0, ")", tokenStreamLocation0);
      TokenStreamLocation tokenStreamLocation1 = jacksonException0.getLocation();
      assertEquals(41, tokenStreamLocation1.getLineNr());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("");
      String string0 = jacksonException0.getLocalizedMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, (-1L), 3365L, (-433), (-433));
      JacksonException jacksonException0 = new JacksonException((Closeable) null, "", tokenStreamLocation0);
      String string0 = JacksonException._exceptionMessage(jacksonException0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, (-1L), 3365L, (-433), (-433));
      JacksonException jacksonException0 = new JacksonException((Closeable) null, "", tokenStreamLocation0);
      String string0 = jacksonException0._buildMessage();
      assertEquals("\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); byte offset: #UNKNOWN]", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("");
      String string0 = jacksonException0._buildMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("Jw#", false);
      InvocationTargetException invocationTargetException0 = new InvocationTargetException((Throwable) null);
      JacksonException jacksonException0 = new JacksonException(mockFileWriter0, "Jw#", invocationTargetException0);
      StringBuilder stringBuilder0 = jacksonException0._appendPathDesc((StringBuilder) null);
      assertNull(stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("i`wWQ6n#Al", false);
      TokenStreamLocation tokenStreamLocation0 = TokenStreamLocation.NA;
      JacksonException jacksonException0 = new JacksonException(mockFileWriter0, "@ROK*zqED{K6", tokenStreamLocation0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "@ROK*zqED{K6");
      StringBuilder stringBuilder1 = jacksonException0._appendPathDesc(stringBuilder0);
      assertSame(stringBuilder0, stringBuilder1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) null, jacksonException_Reference0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) null, (Object) jacksonException_Reference0, "UNKNOWN[\"M/h:t%E.~1>EzzA\"]");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("", (Throwable) null);
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) null, (Object) jacksonException0, 4894);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ContentReference contentReference0 = ContentReference.rawReference(false, (Object) "HFbh'n=6hY.H");
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 274877907L, (-5263L), 0, 1);
      JacksonException jacksonException0 = new JacksonException("HFbh'n=6hY.H", tokenStreamLocation0, (Throwable) null);
      JacksonException jacksonException1 = JacksonException.wrapWithPath((Throwable) jacksonException0, (JacksonException.Reference) null);
      // Undeclared exception!
      try { 
        jacksonException1.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(pipedOutputStream0, charsetEncoder0);
      ContentReference contentReference0 = ContentReference.unknown();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 24, 41, 24);
      JacksonException jacksonException0 = new JacksonException(outputStreamWriter0, ")", tokenStreamLocation0);
      // Undeclared exception!
      try { 
        jacksonException0.prependPath((Object) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot pass null 'propertyName'
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("tools.jackson.core.JacksonException$Reference");
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 3062L, (-1191), (-1580));
      JacksonException jacksonException0 = new JacksonException(mockPrintWriter0, "", tokenStreamLocation0);
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      JacksonException.wrapWithPath((Throwable) jacksonException0, jacksonException_Reference0);
      // Undeclared exception!
      try { 
        jacksonException0.getPathReference((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("*");
      JacksonException jacksonException1 = jacksonException0.prependPath((JacksonException.Reference) null);
      // Undeclared exception!
      try { 
        jacksonException1.getMessage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      JacksonException jacksonException0 = new JacksonException(stringWriter0, "~]w_QV3Qur{H;X");
      BiFunction<String, Throwable, JacksonException> biFunction0 = (BiFunction<String, Throwable, JacksonException>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      JacksonException jacksonException1 = JacksonException.wrapWithPath((Throwable) jacksonException0, (JacksonException.Reference) null, biFunction0);
      // Undeclared exception!
      try { 
        jacksonException1.getLocalizedMessage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        JacksonException._exceptionMessage((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, (-512L), (-512L), 1, 1);
      MockThrowable mockThrowable0 = new MockThrowable(": ");
      JacksonException jacksonException0 = new JacksonException((Closeable) null, "5Cfe|4", tokenStreamLocation0, mockThrowable0);
      JacksonException jacksonException1 = jacksonException0.prependPath((JacksonException.Reference) null);
      // Undeclared exception!
      try { 
        jacksonException1._buildMessage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("SZ!>bz)gQ3d.");
      // Undeclared exception!
      try { 
        jacksonException0._appendReferenceChain((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(mockThrowable0, "tools.jackson.core.JacksonException");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      // Undeclared exception!
      try { 
        jacksonException0._appendPathDesc((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException((Closeable) null, (String) null);
      JacksonException jacksonException1 = JacksonException.wrapWithPath((Throwable) jacksonException0, (Object) jacksonException0, 0);
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      jacksonException1.prependPath(jacksonException_Reference0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      String string0 = JacksonException._exceptionMessage(mockThrowable0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("tools.jackson.core.StreamReadConstraints");
      InvocationTargetException invocationTargetException0 = new InvocationTargetException(jacksonException0, "yYJ=)");
      String string0 = JacksonException._exceptionMessage(invocationTargetException0);
      assertEquals("tools.jackson.core.StreamReadConstraints", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("|a_6e[?6Rt:3)OB");
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      InvocationTargetException invocationTargetException0 = new InvocationTargetException(jacksonException0, "?'#@");
      BiFunction<String, Throwable, JacksonException> biFunction0 = (BiFunction<String, Throwable, JacksonException>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(biFunction0).apply(anyString() , any(java.lang.Throwable.class));
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) invocationTargetException0, jacksonException_Reference0, biFunction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      MockThrowable mockThrowable0 = new MockThrowable((Throwable) null);
      BiFunction<String, Throwable, JacksonException> biFunction0 = (BiFunction<String, Throwable, JacksonException>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(biFunction0).apply(anyString() , any(java.lang.Throwable.class));
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0, biFunction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      
      jacksonException_Reference0._index = 0;
      String string0 = jacksonException_Reference0.getDescription();
      assertEquals("UNKNOWN[0]", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      jacksonException_Reference0.setPropertyName("M/h:t%E.~1>EzzA");
      String string0 = jacksonException_Reference0.getDescription();
      assertNotNull(string0);
      assertEquals("UNKNOWN[\"M/h:t%E.~1>EzzA\"]", string0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(mockThrowable0, "tools.jackson.core.JacksonException");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      TokenStreamLocation tokenStreamLocation0 = jacksonException0.getLocation();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      assertNotNull(tokenStreamLocation0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Object object0 = new Object();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(object0, 91);
      MockThrowable mockThrowable0 = new MockThrowable("Cannot pass null 'propertyName'");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "Cannot pass null 'propertyName'");
      jacksonException0.getPathReference(stringBuilder0);
      assertEquals("Cannot pass null 'propertyName'java.lang.Object[91]", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(mockThrowable0, "tools.jackson.core.JacksonException");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      String string0 = jacksonException0.toString();
      assertEquals("tools.jackson.core.JacksonException: (was org.evosuite.runtime.mock.java.lang.MockThrowable)\n at [No location information] (through reference chain: org.evosuite.runtime.mock.java.lang.MockThrowable[\"tools.jackson.core.JacksonException\"])", string0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1169);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      List<JacksonException.Reference> list0 = jacksonException0.getPath();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(mockThrowable0, "tools.jackson.core.JacksonException");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      List<JacksonException.Reference> list0 = jacksonException0.getPath();
      assertTrue(list0.contains(jacksonException_Reference0));
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1169);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      jacksonException0.prependPath((Object) jacksonException0, "tools.jackson.core.JacksonException");
      JacksonException.wrapWithPath((Throwable) jacksonException0, (Object) "", 1169);
      StringBuilder stringBuilder0 = new StringBuilder();
      jacksonException0._appendReferenceChain(stringBuilder0);
      assertEquals(" (through reference chain: java.lang.String[1169]->tools.jackson.core.JacksonException[\"tools.jackson.core.JacksonException\"])", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      InvocationTargetException invocationTargetException0 = new InvocationTargetException((Throwable) null);
      String string0 = JacksonException._exceptionMessage(invocationTargetException0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      // Undeclared exception!
      try { 
        JacksonException.wrapWithPath((Throwable) mockThrowable0, (JacksonException.Reference) null, (BiFunction<String, Throwable, JacksonException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tools.jackson.core.JacksonException", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectReadContext.Base objectReadContext_Base0 = ObjectReadContext.Base.EMPTY_CONTEXT;
      JsonParser jsonParser0 = jsonFactory0.createNonBlockingByteBufferParser(objectReadContext_Base0);
      MockThrowable mockThrowable0 = new MockThrowable("](O3ApjnE%");
      JacksonException jacksonException0 = new JacksonException(jsonParser0, "](O3ApjnE%", mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1169);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      JacksonException jacksonException1 = new JacksonException(pipedReader0, "tools.jackson.core.JacksonException", jacksonException0);
      assertFalse(jacksonException1.equals((Object)jacksonException0));
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectReadContext.Base objectReadContext_Base0 = new ObjectReadContext.Base();
      byte[] byteArray0 = new byte[1];
      JsonParser jsonParser0 = jsonFactory0.createParser((ObjectReadContext) objectReadContext_Base0, byteArray0);
      JacksonException jacksonException0 = new JacksonException(jsonParser0, "JSON");
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      
      jacksonException_Reference0._index = 1169;
      String string0 = jacksonException_Reference0.toString();
      assertEquals("UNKNOWN[1169]", string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      jacksonException_Reference0.setDescription("Hu:y=");
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      assertEquals((-1), jacksonException_Reference0.getIndex());
      
      jacksonException_Reference0.setIndex(0);
      assertEquals(0, jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      int int0 = jacksonException_Reference0.getIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      jacksonException_Reference0.writeReplace();
      String string0 = jacksonException_Reference0.getDescription();
      assertEquals("UNKNOWN[?]", string0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(pipedOutputStream0, charsetEncoder0);
      ContentReference contentReference0 = ContentReference.unknown();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 24, 41, 24);
      JacksonException jacksonException0 = new JacksonException(outputStreamWriter0, ")", tokenStreamLocation0);
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(jacksonException0, ")");
      Object object0 = jacksonException_Reference0.from();
      assertNotNull(object0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException("tools.jackson.core.StreamReadConstraints");
      InvocationTargetException invocationTargetException0 = new InvocationTargetException(jacksonException0, "yYJ=)");
      JacksonException jacksonException1 = JacksonException.wrapWithPath((Throwable) invocationTargetException0, (Object) jacksonException0, "UNKNOWN");
      assertNotSame(jacksonException1, jacksonException0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("tools.jackson.core.JacksonException$Reference");
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 3062L, (-1191), (-1580));
      JacksonException jacksonException0 = new JacksonException(mockPrintWriter0, "", tokenStreamLocation0);
      JacksonException jacksonException1 = jacksonException0.clearLocation();
      assertSame(jacksonException0, jacksonException1);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("Jw#", false);
      InvocationTargetException invocationTargetException0 = new InvocationTargetException((Throwable) null);
      JacksonException jacksonException0 = new JacksonException(mockFileWriter0, "Jw#", invocationTargetException0);
      // Undeclared exception!
      try { 
        jacksonException0.withCause(invocationTargetException0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Can't overwrite cause with java.lang.reflect.InvocationTargetException
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockThrowable", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference(mockThrowable0, "tools.jackson.core.JacksonException");
      JacksonException jacksonException0 = JacksonException.wrapWithPath((Throwable) mockThrowable0, jacksonException_Reference0);
      jacksonException0.processor();
      assertEquals((-1), jacksonException_Reference0.getIndex());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException((String) null);
      JacksonException jacksonException1 = new JacksonException((Closeable) null, jacksonException0);
      assertFalse(jacksonException1.equals((Object)jacksonException0));
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("tools.jackson.core.JacksonException$Reference");
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 3062L, (-1191), (-1580));
      JacksonException jacksonException0 = new JacksonException(mockPrintWriter0, "", tokenStreamLocation0);
      JacksonException jacksonException1 = new JacksonException(jacksonException0);
      assertFalse(jacksonException1.equals((Object)jacksonException0));
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("tools.jackson.core.JacksonException$Reference");
      ContentReference contentReference0 = ContentReference.redacted();
      TokenStreamLocation tokenStreamLocation0 = new TokenStreamLocation(contentReference0, 3062L, (-1191), (-1580));
      JacksonException jacksonException0 = new JacksonException(mockPrintWriter0, "", tokenStreamLocation0);
      JacksonException.Reference jacksonException_Reference0 = new JacksonException.Reference();
      JacksonException.wrapWithPath((Throwable) jacksonException0, jacksonException_Reference0);
      assertEquals((-1), jacksonException_Reference0.getIndex());
      
      String string0 = jacksonException0.getLocalizedMessage();
      assertEquals("\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); byte offset: #UNKNOWN] (through reference chain: UNKNOWN[?])", string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      JacksonException jacksonException0 = new JacksonException((String) null);
      String string0 = jacksonException0.getOriginalMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1169);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      String string0 = jacksonException0.getMessage();
      assertEquals("8fMbtt)Z$c_G~1\n at [No location information]", string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader(1169);
      JacksonException jacksonException0 = new JacksonException(pipedReader0, "8fMbtt)Z$c_G~1");
      String string0 = jacksonException0.getPathReference();
      assertEquals("", string0);
  }
}
