/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 27 11:33:11 GMT 2026
 */

package tools.jackson.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.FormatFlagsConversionMismatchException;
import java.util.IllegalFormatConversionException;
import java.util.MissingFormatArgumentException;
import java.util.UnknownFormatConversionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tools.jackson.core.StreamReadConstraints;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StreamReadConstraints_ESTest extends StreamReadConstraints_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0.validateBigIntegerScale((-2146012767));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // BigDecimal scale (-2146012767) magnitude exceeds the maximum allowed (100000)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateBigIntegerScale(100000);
      assertEquals(1000, streamReadConstraints0.getMaxNumberLength());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateBigIntegerScale((-2144));
      assertEquals(50000, streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(1042, 0L, 1042, 1042, (-2782), (-4004));
      try { 
        streamReadConstraints0.validateNameLength(2527);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Name length (2527) exceeds the maximum allowed (-4004, from `StreamReadConstraints.getMaxNameLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateNameLength((-1632));
      assertFalse(streamReadConstraints0.hasMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 0);
      streamReadConstraints0.validateStringLengthLong(0);
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0.validateStringLengthLong(2146739544);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // String value length (2146739544) exceeds the maximum allowed (100000000, from `StreamReadConstraints.getMaxStringLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, (-295L), (-295L), (-1870), (-3157), 0);
      try { 
        streamReadConstraints0.validateStringLength(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // String value length (0) exceeds the maximum allowed (-3157, from `StreamReadConstraints.getMaxStringLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateStringLength(0);
      assertEquals((-1L), StreamReadConstraints.DEFAULT_MAX_TOKEN_COUNT);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0.validateIntegerLength(50000);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Number value length (50000) exceeds the maximum allowed (1000, from `StreamReadConstraints.getMaxNumberLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateIntegerLength((-3535));
      assertFalse(streamReadConstraints0.hasMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0L, 0, 0, (-188));
      streamReadConstraints0.validateFPLength(0);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-188), streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0.validateFPLength(2241);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Number value length (2241) exceeds the maximum allowed (1000, from `StreamReadConstraints.getMaxNumberLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, (-1052L), 0L, 0, 0, 0);
      try { 
        streamReadConstraints0.validateTokenCount(2188L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token count (2188) exceeds the maximum allowed (0, from `StreamReadConstraints.getMaxTokenCount()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateTokenCount((-966L));
      assertEquals(500, StreamReadConstraints.DEFAULT_MAX_DEPTH);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(100000, 584, 100000, 3469, 3469, 584);
      try { 
        streamReadConstraints0.validateDocumentLength(3469);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Document length (3469) exceeds the maximum allowed (584, from `StreamReadConstraints.getMaxDocumentLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateDocumentLength(50000);
      assertEquals(100000000, StreamReadConstraints.DEFAULT_MAX_STRING_LEN);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-982), (-982), (-1224L), (-404), 93, (-404));
      streamReadConstraints0.validateDocumentLength((-982));
      assertEquals((-982L), streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-404), streamReadConstraints0.getMaxNumberLength());
      assertEquals((-982), streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-1224L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(93, streamReadConstraints0.getMaxStringLength());
      assertEquals((-404), streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0.validateNestingDepth(1000);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Document nesting depth (1000) exceeds the maximum allowed (500, from `StreamReadConstraints.getMaxNestingDepth()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateNestingDepth(0);
      assertEquals(1000, streamReadConstraints0.getMaxNumberLength());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      int int0 = streamReadConstraints0.getMaxNameLength();
      assertEquals(50000, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0L, 730, 0, 0);
      boolean boolean0 = streamReadConstraints0.hasMaxTokenCount();
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertFalse(boolean0);
      assertEquals(730, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      boolean boolean0 = streamReadConstraints0.hasMaxDocumentLength();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = new StreamReadConstraints.Builder((-2764), 1L, (-2764), (-2764), Integer.MAX_VALUE, (-2764));
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(3961, 795L, (-1963L), 3961, (-1574), 0);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      streamReadConstraints_Builder0.maxNameLength(0);
      assertEquals((-1574), streamReadConstraints0.getMaxStringLength());
      assertEquals((-1963L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(3961, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(3961, streamReadConstraints0.getMaxNumberLength());
      assertTrue(streamReadConstraints0.hasMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxStringLength(0);
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(3961, 795L, (-1963L), 3961, (-1574), 0);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      streamReadConstraints_Builder0.maxNumberLength(0);
      assertEquals((-1574), streamReadConstraints0.getMaxStringLength());
      assertEquals((-1963L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(3961, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertTrue(streamReadConstraints0.hasMaxDocumentLength());
      assertEquals(3961, streamReadConstraints0.getMaxNumberLength());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxTokenCount((-1734L));
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxDocumentLength((-1197L));
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxNestingDepth(0);
      assertSame(streamReadConstraints_Builder1, streamReadConstraints_Builder0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-2503), (-2503), (-2503), (-286), (-286), 19);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = new StreamReadConstraints.Builder(streamReadConstraints0);
      assertEquals((-2503), streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-2503L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(19, streamReadConstraints0.getMaxNameLength());
      assertEquals((-2503L), streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-286), streamReadConstraints0.getMaxNumberLength());
      assertEquals((-286), streamReadConstraints0.getMaxStringLength());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = new StreamReadConstraints.Builder();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(1769, 0L, 1769, (-1), 155, 1769);
      long long0 = streamReadConstraints0.getMaxTokenCount();
      assertEquals((-1), streamReadConstraints0.getMaxNumberLength());
      assertEquals(1769L, long0);
      assertEquals(1769, streamReadConstraints0.getMaxNameLength());
      assertEquals(155, streamReadConstraints0.getMaxStringLength());
      assertEquals(1769, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 1L, (-193L), 0, 0, 0);
      long long0 = streamReadConstraints0.getMaxTokenCount();
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(1L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals((-193L), long0);
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(10, 1L, 1L, 10, 10, 10);
      int int0 = streamReadConstraints0.getMaxStringLength();
      assertEquals(10, int0);
      assertEquals(10, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(1L, streamReadConstraints0.getMaxTokenCount());
      assertTrue(streamReadConstraints0.hasMaxDocumentLength());
      assertEquals(10, streamReadConstraints0.getMaxNumberLength());
      assertEquals(10, streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(3961, 795L, (-1963L), 3961, (-1574), 0);
      int int0 = streamReadConstraints0.getMaxStringLength();
      assertEquals(3961, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(3961, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(795L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-1574), int0);
      assertEquals((-1963L), streamReadConstraints0.getMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0L, 0L, 0, 0, 2508);
      int int0 = streamReadConstraints0.getMaxNumberLength();
      assertEquals(0, int0);
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-982), (-982), (-1224L), (-404), 93, (-404));
      int int0 = streamReadConstraints0.getMaxNumberLength();
      assertEquals((-982L), streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-1224L), streamReadConstraints0.getMaxTokenCount());
      assertEquals((-982), streamReadConstraints0.getMaxNestingDepth());
      assertEquals(93, streamReadConstraints0.getMaxStringLength());
      assertEquals((-404), streamReadConstraints0.getMaxNameLength());
      assertEquals((-404), int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      int int0 = streamReadConstraints0.getMaxNestingDepth();
      assertEquals(500, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-3254), 0L, (-3254), (-3254), (-3431), (-3254));
      int int0 = streamReadConstraints0.getMaxNestingDepth();
      assertEquals((-3254), streamReadConstraints0.getMaxNameLength());
      assertEquals((-3254L), streamReadConstraints0.getMaxTokenCount());
      assertEquals((-3254), int0);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-3254), streamReadConstraints0.getMaxNumberLength());
      assertEquals((-3431), streamReadConstraints0.getMaxStringLength());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 1L, (-193L), 0, 0, 0);
      int int0 = streamReadConstraints0.getMaxNameLength();
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertTrue(streamReadConstraints0.hasMaxDocumentLength());
      assertEquals(0, int0);
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-193L), streamReadConstraints0.getMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(50000, 50000, 1326L, (-808), (-808), (-808));
      int int0 = streamReadConstraints0.getMaxNameLength();
      assertEquals((-808), streamReadConstraints0.getMaxNumberLength());
      assertEquals((-808), streamReadConstraints0.getMaxStringLength());
      assertEquals(50000, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(50000L, streamReadConstraints0.getMaxDocumentLength());
      assertTrue(streamReadConstraints0.hasMaxTokenCount());
      assertEquals((-808), int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, (-284L), 0, (-174), (-174));
      long long0 = streamReadConstraints0.getMaxDocumentLength();
      assertEquals((-174), streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals((-174), streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-284L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(410, 410, (-1477L), 410, 0, 410);
      long long0 = streamReadConstraints0.getMaxDocumentLength();
      assertEquals(410L, long0);
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(410, streamReadConstraints0.getMaxNameLength());
      assertEquals(410, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(410, streamReadConstraints0.getMaxNumberLength());
      assertEquals((-1477L), streamReadConstraints0.getMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, Integer.MAX_VALUE, Integer.MAX_VALUE);
      StreamReadConstraints.overrideDefaultStreamReadConstraints(streamReadConstraints0);
      StreamReadConstraints streamReadConstraints1 = StreamReadConstraints.defaults();
      assertEquals(Integer.MAX_VALUE, streamReadConstraints1.getMaxStringLength());
      assertEquals(0, streamReadConstraints1.getMaxNumberLength());
      assertEquals(0, streamReadConstraints1.getMaxNestingDepth());
      assertEquals(Integer.MAX_VALUE, streamReadConstraints1.getMaxNameLength());
      assertEquals(0L, streamReadConstraints1.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-4362), (-4362), 1641L, 1717986918, (-4362), (-1237));
      StreamReadConstraints.overrideDefaultStreamReadConstraints(streamReadConstraints0);
      StreamReadConstraints streamReadConstraints1 = StreamReadConstraints.defaults();
      assertEquals(1717986918, streamReadConstraints1.getMaxNumberLength());
      assertEquals((-4362), streamReadConstraints1.getMaxNestingDepth());
      assertEquals((-4362L), streamReadConstraints1.getMaxDocumentLength());
      assertEquals(1641L, streamReadConstraints1.getMaxTokenCount());
      assertEquals((-4362), streamReadConstraints1.getMaxStringLength());
      assertEquals((-1237), streamReadConstraints1.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-1001), 0L, (-1L), (-1001), 0, 50000);
      StreamReadConstraints.overrideDefaultStreamReadConstraints(streamReadConstraints0);
      StreamReadConstraints streamReadConstraints1 = StreamReadConstraints.defaults();
      assertEquals((-1L), streamReadConstraints1.getMaxTokenCount());
      assertEquals((-1001), streamReadConstraints1.getMaxNumberLength());
      assertEquals((-1001), streamReadConstraints1.getMaxNestingDepth());
      assertEquals(0L, streamReadConstraints1.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints1.getMaxStringLength());
      assertEquals(50000, streamReadConstraints1.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 1L, (-193L), 0, 0, 0);
      StreamReadConstraints.overrideDefaultStreamReadConstraints(streamReadConstraints0);
      StreamReadConstraints streamReadConstraints1 = StreamReadConstraints.defaults();
      assertEquals((-193L), streamReadConstraints1.getMaxTokenCount());
      assertEquals(0, streamReadConstraints1.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints1.getMaxNumberLength());
      assertEquals(0, streamReadConstraints1.getMaxStringLength());
      assertEquals(0, streamReadConstraints1.getMaxNameLength());
      assertTrue(streamReadConstraints1.hasMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      try { 
        streamReadConstraints0._constructException("", (Object[]) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(1, 1, 1, 1, 1, 1);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        streamReadConstraints0._constructException("u_YJ~f:%3q0%ZN?^U", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'q'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(1641, 1641, 1000L, 1641, 1641, 500);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        streamReadConstraints0._constructException("Document nesting depth (%d) exceeds the maximum allowed (%d, from %s)", objectArray0);
        fail("Expecting exception: MissingFormatArgumentException");
      
      } catch(MissingFormatArgumentException e) {
         //
         // Format specifier '%d'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(500, 2405L, 2405L, 500, 500, 40);
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) streamReadConstraints0;
      // Undeclared exception!
      try { 
        streamReadConstraints0._constructException("`StreamReadConstraints.Name length (%d) exceeds the maximum allowed (%d, from %s)()`", objectArray0);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // d != tools.jackson.core.StreamReadConstraints
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      // Undeclared exception!
      try { 
        streamReadConstraints0._constructException(")%+tDJq8W GeIj", (Object[]) null);
        fail("Expecting exception: FormatFlagsConversionMismatchException");
      
      } catch(FormatFlagsConversionMismatchException e) {
         //
         // Conversion = D, Flags = +
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      Object[] objectArray0 = new Object[9];
      // Undeclared exception!
      try { 
        streamReadConstraints0._constructException((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 3265L, 0, 0, 0);
      streamReadConstraints0.validateNameLength(0);
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertTrue(streamReadConstraints0.hasMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-3365), 2036L, 2020L, (-3365), (-3365), 0);
      try { 
        streamReadConstraints0.validateStringLengthLong(2020L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // String value length (2020) exceeds the maximum allowed (-3365, from `StreamReadConstraints.getMaxStringLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(2, 2, (-1L), 2, 1, 2);
      streamReadConstraints0.validateStringLengthLong((-1L));
      assertEquals(1, streamReadConstraints0.getMaxStringLength());
      assertEquals(2, streamReadConstraints0.getMaxNameLength());
      assertEquals(2L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals((-1L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(2, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(2, streamReadConstraints0.getMaxNumberLength());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 0);
      streamReadConstraints0.validateStringLength(0);
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, (-1729), 2, 2);
      try { 
        streamReadConstraints0.validateIntegerLength(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Number value length (0) exceeds the maximum allowed (-1729, from `StreamReadConstraints.getMaxNumberLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      streamReadConstraints0.validateIntegerLength(1000);
      assertFalse(streamReadConstraints0.hasMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 3265L, 0, 0, 0);
      try { 
        streamReadConstraints0.validateFPLength(50000);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Number value length (50000) exceeds the maximum allowed (0, from `StreamReadConstraints.getMaxNumberLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      streamReadConstraints0.validateFPLength((-3005));
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-566), (-364L), 0L, (-566), (-566), 0);
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      
      streamReadConstraints0.validateTokenCount(0L);
      assertEquals((-566), streamReadConstraints0.getMaxNumberLength());
      assertEquals((-566), streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals((-566), streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-364L), streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 3265L, 0, 0, 0);
      streamReadConstraints0.validateDocumentLength(2283L);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(3265L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints streamReadConstraints0 = streamReadConstraints_Builder0.build();
      streamReadConstraints0.validateDocumentLength((-1051L));
      assertEquals((-1L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(500, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(100000000, streamReadConstraints0.getMaxStringLength());
      assertEquals(1000, streamReadConstraints0.getMaxNumberLength());
      assertEquals((-1L), streamReadConstraints0.getMaxDocumentLength());
      assertEquals(50000, streamReadConstraints0.getMaxNameLength());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, Integer.MAX_VALUE, Integer.MAX_VALUE);
      try { 
        streamReadConstraints0.validateNestingDepth(2956);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Document nesting depth (2956) exceeds the maximum allowed (0, from `StreamReadConstraints.getMaxNestingDepth()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      streamReadConstraints0.validateNestingDepth(0);
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 3265L, 0, 0, 0);
      boolean boolean0 = streamReadConstraints0.hasMaxTokenCount();
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      boolean boolean0 = streamReadConstraints0.hasMaxTokenCount();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(768, 768, 768, 768, 768, 768);
      boolean boolean0 = streamReadConstraints0.hasMaxDocumentLength();
      assertEquals(768, streamReadConstraints0.getMaxNumberLength());
      assertEquals(768, streamReadConstraints0.getMaxStringLength());
      assertTrue(streamReadConstraints0.hasMaxTokenCount());
      assertEquals(768, streamReadConstraints0.getMaxNameLength());
      assertEquals(768, streamReadConstraints0.getMaxNestingDepth());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 3265L, 0, 0, 0);
      boolean boolean0 = streamReadConstraints0.hasMaxDocumentLength();
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(3265L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = new StreamReadConstraints.Builder(456, 456, 456, 0, (-1242), 0);
      // Undeclared exception!
      try { 
        streamReadConstraints_Builder0.maxNameLength((-1242));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot set maxNameLen to a negative value
         //
         verifyException("tools.jackson.core.StreamReadConstraints$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      streamReadConstraints_Builder0.maxNameLength(2655);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      // Undeclared exception!
      try { 
        streamReadConstraints_Builder0.maxStringLength((-4072));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot set maxStringLen to a negative value
         //
         verifyException("tools.jackson.core.StreamReadConstraints$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxStringLength(3224);
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      // Undeclared exception!
      try { 
        streamReadConstraints_Builder0.maxNumberLength((-88));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot set maxNumberLength to a negative value
         //
         verifyException("tools.jackson.core.StreamReadConstraints$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxNumberLength(500);
      assertSame(streamReadConstraints_Builder1, streamReadConstraints_Builder0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      streamReadConstraints_Builder0.maxTokenCount(0);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxTokenCount(1958L);
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 613L, 0, 0, Integer.MAX_VALUE, 0);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      streamReadConstraints_Builder0.maxDocumentLength(0L);
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(Integer.MAX_VALUE, streamReadConstraints0.getMaxStringLength());
      assertTrue(streamReadConstraints0.hasMaxDocumentLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(613L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxDocumentLength(1L);
      assertSame(streamReadConstraints_Builder0, streamReadConstraints_Builder1);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      // Undeclared exception!
      try { 
        streamReadConstraints_Builder0.maxNestingDepth((-2910));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot set maxNestingDepth to a negative value
         //
         verifyException("tools.jackson.core.StreamReadConstraints$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      StreamReadConstraints.overrideDefaultStreamReadConstraints((StreamReadConstraints) null);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints((-566), (-364L), 0L, (-566), (-566), 0);
      try { 
        streamReadConstraints0.validateStringLength(500);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // String value length (500) exceeds the maximum allowed (-566, from `StreamReadConstraints.getMaxStringLength()`)
         //
         verifyException("tools.jackson.core.StreamReadConstraints", e);
      }
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 2508);
      int int0 = streamReadConstraints0.getMaxStringLength();
      assertEquals(2508, streamReadConstraints0.getMaxNameLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, int0);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      long long0 = streamReadConstraints0.getMaxDocumentLength();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 0);
      String string0 = streamReadConstraints0._constrainRef((String) null);
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals("`StreamReadConstraints.null()`", string0);
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 0);
      int int0 = streamReadConstraints0.getMaxNestingDepth();
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0, int0);
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0L, streamReadConstraints0.getMaxTokenCount());
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = new StreamReadConstraints(0, 0, 0, 0, 0, 0);
      long long0 = streamReadConstraints0.getMaxTokenCount();
      assertEquals(0L, streamReadConstraints0.getMaxDocumentLength());
      assertEquals(0, streamReadConstraints0.getMaxNameLength());
      assertEquals(0, streamReadConstraints0.getMaxNestingDepth());
      assertEquals(0, streamReadConstraints0.getMaxStringLength());
      assertEquals(0, streamReadConstraints0.getMaxNumberLength());
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      StreamReadConstraints streamReadConstraints0 = StreamReadConstraints.defaults();
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = streamReadConstraints0.rebuild();
      StreamReadConstraints.Builder streamReadConstraints_Builder1 = streamReadConstraints_Builder0.maxNestingDepth(1000);
      assertSame(streamReadConstraints_Builder1, streamReadConstraints_Builder0);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      StreamReadConstraints.Builder streamReadConstraints_Builder0 = StreamReadConstraints.builder();
      StreamReadConstraints streamReadConstraints0 = streamReadConstraints_Builder0.build();
      int int0 = streamReadConstraints0.getMaxNumberLength();
      assertEquals(500, streamReadConstraints0.getMaxNestingDepth());
      assertEquals((-1L), streamReadConstraints0.getMaxTokenCount());
      assertEquals(100000000, streamReadConstraints0.getMaxStringLength());
      assertEquals(50000, streamReadConstraints0.getMaxNameLength());
      assertEquals(1000, int0);
      assertEquals((-1L), streamReadConstraints0.getMaxDocumentLength());
  }
}
